[general]
import = [
    "~/.config/alacritty/themes/themes/gineikacc.toml"
]
[font]
size = 13
normal = { family = "Iosevka", style = "Regular" }

[colors]
selection = { text = "#FFFFFF", background = "#000000" }

[terminal.shell]
program = "/home/blud/code/scripts/ghostty-exec.sh"

